apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: azure-test 
  janus-idp.io/tekton: azure-test
  backstage.io/kubernetes-id: azure-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: azure-test
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml